[unstable]
json-target-spec = true
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "spec/riscv32im-unknown-cinnamos.json"

[target.riscv32im-unknown-cinnamos]
rustflags = [
    "-C", "link-arg=-Tcrates/kernel/src/boot/linker.ld",
]
runner = """\
qemu-system-riscv32 \
-machine virt \
-nographic \
-m 128M \
-serial pty \
-bios default \
-kernel \
"""
