[unstable]
json-target-spec = true
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "spec/riscv32imac-unknown-cinnamos.json"

[target.riscv32imac-unknown-cinnamos]
rustflags = [
    "-C", "link-arg=-Tcrates/cinnamos-kernel/src/ld/arch/riscv32.ld",
]
runner = "scripts/run-qemu-riscv32.sh"
