[unstable]
json-target-spec = true
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "spec/riscv32imac-unknown-cinnamos.json"

[target.'cfg(target_os = "cinnamos")']
rustflags = [
    "-C", "link-arg=-Tcrates/kernel/src/boot/linker.ld",
]
runner = "./run-qemu.sh"
